Repository yanJuicy/hanghae-blog-api, pull requests merged in 2022-12, with the labels that each got.

#2 feat: common 패키지 작성
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionResponseDto.java
  src/main/java/com/hanghae/blog/api/common/response/GenericResponseDto.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
Labels: feature

#4 feat: Posting 생성 API 작업
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/RequestCreatePostingDto.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponseCreatePostingDto.java
  src/main/java/com/hanghae/blog/api/posting/entity/Posting.java
  src/main/java/com/hanghae/blog/api/posting/exception/PostingExceptionHandler.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/repository/PostingRepository.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#6 feat: H2 properties 추가
  src/main/resources/application.properties
Labels: feature

#9 feat: Timestamped 엔터티 추가
  src/main/java/com/hanghae/blog/api/HanghaeBlogApiApplication.java
  src/main/java/com/hanghae/blog/api/common/entity/Timestamped.java
Labels: feature

#22 refactor: 스프링부트 버전 변경
  build.gradle
  src/main/java/com/hanghae/blog/api/common/entity/Timestamped.java
  src/main/java/com/hanghae/blog/api/posting/entity/Posting.java
Labels: refactor

#25 feat: 카테고리 엔터티 및 패키지 생성
  src/main/java/com/hanghae/blog/api/category/entity/Category.java
  src/main/java/com/hanghae/blog/api/category/entity/Category_Posting_Map.java
  src/main/java/com/hanghae/blog/api/posting/entity/Posting.java
Labels: feature

#29 ♻️ Refactor: ResponseDto 재구조화
  src/main/java/com/hanghae/blog/api/comment/controller/CommentController.java
  src/main/java/com/hanghae/blog/api/comment/exception/CommentExceptionHandler.java
  src/main/java/com/hanghae/blog/api/comment/mapper/CommentMapper.java
  src/main/java/com/hanghae/blog/api/comment/service/CommentService.java
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionResponseDto.java
  src/main/java/com/hanghae/blog/api/common/response/DataResponse.java
  src/main/java/com/hanghae/blog/api/common/response/GenericResponseDto.java
  src/main/java/com/hanghae/blog/api/common/response/Response.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: refactor

#31 📝 Doc: PR 템플릿 규칙 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#26 ✨ feat: 게시물 등록 API 기능 추가
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/RequestCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponseCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#36 feat: 전체 게시글 조회 API기능 추가
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponseCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#38 ♻️Refactor: 회원가입 Refactor
  src/main/java/com/hanghae/blog/api/User/exception/UserExceptionHandler.java
  src/main/java/com/hanghae/blog/api/User/mapper/UserMapper.java
  src/main/java/com/hanghae/blog/api/User/service/UserService.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
Labels: refactor

#43 ✨ Feat: 로그인 API
  .gitignore
  build.gradle
  src/main/java/com/hanghae/blog/api/User/service/UserService.java
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
  src/main/java/com/hanghae/blog/api/jwt/JwtUtil.java
  src/main/java/com/hanghae/blog/api/user/contorller/UserController.java
  src/main/java/com/hanghae/blog/api/user/dto/RequestCreateUser.java
  src/main/java/com/hanghae/blog/api/user/dto/RequestFindUser.java
  src/main/java/com/hanghae/blog/api/user/entity/User.java
  src/main/java/com/hanghae/blog/api/user/entity/UserRoleEnum.java
  src/main/java/com/hanghae/blog/api/user/exception/UserExceptionHandler.java
  src/main/java/com/hanghae/blog/api/user/mapper/UserMapper.java
  src/main/java/com/hanghae/blog/api/user/repository/UserRepository.java
  src/main/java/com/hanghae/blog/api/user/service/UserService.java
  src/main/resources/application.properties
Labels: feature

#39 ✨ Feat: 댓글 수정 API
  src/main/java/com/hanghae/blog/api/comment/controller/CommentController.java
  src/main/java/com/hanghae/blog/api/comment/dto/RequestComment.java
  src/main/java/com/hanghae/blog/api/comment/dto/ResponseComment.java
  src/main/java/com/hanghae/blog/api/comment/entity/Comment.java
  src/main/java/com/hanghae/blog/api/comment/exception/CommentExceptionHandler.java
  src/main/java/com/hanghae/blog/api/comment/mapper/CommentMapper.java
  src/main/java/com/hanghae/blog/api/comment/service/CommentService.java
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponseCreatePosting.java
  src/main/resources/application.properties
Labels: feature

#44 ✨ Feat: 댓글 삭제 API
  src/main/java/com/hanghae/blog/api/comment/controller/CommentController.java
  src/main/java/com/hanghae/blog/api/comment/service/CommentService.java
  src/main/java/com/hanghae/blog/api/common/response/Response.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
Labels: feature

#45 ✨ Feat: 게시글 페이징 조회 API
  src/main/java/com/hanghae/blog/api/common/response/PageResponse.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/RequestPagePosting.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponsePosting.java
  src/main/java/com/hanghae/blog/api/posting/entity/Posting.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#48 ♻️ Refactor: ResponseMessage controller에서 반환
  src/main/java/com/hanghae/blog/api/comment/controller/CommentController.java
  src/main/java/com/hanghae/blog/api/comment/service/CommentService.java
Labels: refactor

#49 feat: 선택 게시글 조회
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#51 ♻️ Refactor: Posting 도메인 응답 dto 컨벤션 맞춤
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: refactor

#53 🐛 Fix: Update RequestCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/dto/RequestCreatePosting.java
Labels: refactor

#50 ✨ Feat: 토큰 및 씨큐리티 API
  .gitignore
  build.gradle
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/blog/api/common/response/Response.java
  src/main/java/com/hanghae/blog/api/config/WebSecurityConfig.java
  src/main/java/com/hanghae/blog/api/jwt/JwtAuthFilter.java
  src/main/java/com/hanghae/blog/api/jwt/JwtUtil.java
  src/main/java/com/hanghae/blog/api/security/UserDetailsImpl.java
  src/main/java/com/hanghae/blog/api/security/UserDetailsServiceImpl.java
  src/main/java/com/hanghae/blog/api/user/contorller/UserController.java
  src/main/java/com/hanghae/blog/api/user/entity/UserRoleEnum.java
  src/main/java/com/hanghae/blog/api/user/mapper/UserMapper.java
  src/main/java/com/hanghae/blog/api/user/service/UserService.java
  src/main/resources/application.properties
Labels: feature

#52 ✨ Feat: 대댓글 생성 API
  src/main/java/com/hanghae/blog/api/comment/controller/CommentController.java
  src/main/java/com/hanghae/blog/api/comment/dto/ResponseComment.java
  src/main/java/com/hanghae/blog/api/comment/entity/Comment.java
  src/main/java/com/hanghae/blog/api/comment/mapper/CommentMapper.java
  src/main/java/com/hanghae/blog/api/comment/repository/CommentRepository.java
  src/main/java/com/hanghae/blog/api/comment/service/CommentService.java
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
Labels: feature

#56 ♻️ Refactor: PostingMapper 리팩터링
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/RequestCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponseCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: refactor

#58 ♻️ Refactor: JwtAuthFilter 리펙토링
  src/main/java/com/hanghae/blog/api/jwt/JwtAuthFilter.java
Labels: refactor

#62 ✨ Feat: 댓글 좋아요 및 좋아요 취소 API
  src/main/java/com/hanghae/blog/api/comment/entity/Comment.java
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
  src/main/java/com/hanghae/blog/api/like/controller/CommentLikeController.java
  src/main/java/com/hanghae/blog/api/like/dto/comments/LikeState.java
  src/main/java/com/hanghae/blog/api/like/entity/CommentLike.java
  src/main/java/com/hanghae/blog/api/like/exception/CommentLikeExceptionHandler.java
  src/main/java/com/hanghae/blog/api/like/mapper/CommentLikeMapper.java
  src/main/java/com/hanghae/blog/api/like/repository/CommentLikeRepository.java
  src/main/java/com/hanghae/blog/api/like/service/CommentLikeService.java
Labels: feature

#63 ✨ feat: 게시글 수정 API
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/entity/Posting.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#65 🐛 Fix: 댓글 삭제 로직 수정
  src/main/java/com/hanghae/blog/api/comment/controller/CommentController.java
  src/main/java/com/hanghae/blog/api/comment/repository/CommentRepository.java
  src/main/java/com/hanghae/blog/api/comment/service/CommentService.java
Labels: fix

#70 ♻️ Refactor: 403예외처리
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/blog/api/config/WebSecurityConfig.java
  src/main/java/com/hanghae/blog/api/jwt/JwtAuthFilter.java
Labels: refactor

#72 ✨ Feat: 회원 탈퇴 API
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
  src/main/java/com/hanghae/blog/api/config/WebSecurityConfig.java
  src/main/java/com/hanghae/blog/api/jwt/JwtAuthFilter.java
  src/main/java/com/hanghae/blog/api/security/UserDetailsServiceImpl.java
  src/main/java/com/hanghae/blog/api/user/contorller/UserController.java
  src/main/java/com/hanghae/blog/api/user/entity/User.java
  src/main/java/com/hanghae/blog/api/user/mapper/UserMapper.java
  src/main/java/com/hanghae/blog/api/user/service/UserService.java
Labels: feature

#67 ✨feat: 게시글 삭제 API
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#78 ♻️ Refactor: Posting Exception 메시지 설정 및 수정
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
  src/main/java/com/hanghae/blog/api/common/response/ResponseMessage.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/exception/PostingExceptionHandler.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: refactor

#73 ✨Feat: comment API 유저 정보 추가
  src/main/java/com/hanghae/blog/api/comment/controller/CommentController.java
  src/main/java/com/hanghae/blog/api/comment/mapper/CommentMapper.java
  src/main/java/com/hanghae/blog/api/comment/service/CommentService.java
  src/main/java/com/hanghae/blog/api/common/exception/ExceptionMessage.java
Labels: feature

#79 ✨ Feat, ♻️ Refactor: like 도메인 수정
  src/main/java/com/hanghae/blog/api/comment/entity/Comment.java
  src/main/java/com/hanghae/blog/api/like/controller/LikeController.java
  src/main/java/com/hanghae/blog/api/like/dto/LikeState.java
  src/main/java/com/hanghae/blog/api/like/entity/CommentLike.java
  src/main/java/com/hanghae/blog/api/like/exception/CommentLikeExceptionHandler.java
  src/main/java/com/hanghae/blog/api/like/mapper/CommentLikeMapper.java
  src/main/java/com/hanghae/blog/api/like/service/LikeService.java
Labels: feature, refactor

#81 ✨ Feat: 카테고리 생성 API
  src/main/java/com/hanghae/blog/api/category/entity/Category.java
  src/main/java/com/hanghae/blog/api/category/repository/CategoryRepository.java
  src/main/java/com/hanghae/blog/api/category/service/CategoryService.java
  src/main/java/com/hanghae/blog/api/category_posting_map/entity/CategoryPostingMap.java
  src/main/java/com/hanghae/blog/api/category_posting_map/repository/CategoryPostingMapRepository.java
  src/main/java/com/hanghae/blog/api/category_posting_map/service/CategoryPostingMapService.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/RequestCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponsePosting.java
  src/main/java/com/hanghae/blog/api/posting/entity/Posting.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#83 ♻️refactor: 게시글 조회 API 리펙토링
  src/main/java/com/hanghae/blog/api/comment/repository/CommentRepository.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponsePosting.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: refactor

#84 ✨ Feat: 카테고리별 포스팅 조회 API
  src/main/java/com/hanghae/blog/api/category_posting_map/repository/CategoryPostingMapRepository.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#87 ✨ feat: 게시글 수정 API 재구성
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#89 ✨feat: 게시글 삭제 API 수정
  src/main/java/com/hanghae/blog/api/category_posting_map/repository/CategoryPostingMapRepository.java
  src/main/java/com/hanghae/blog/api/category_posting_map/service/CategoryPostingMapService.java
  src/main/java/com/hanghae/blog/api/comment/controller/CommentController.java
  src/main/java/com/hanghae/blog/api/comment/repository/CommentRepository.java
  src/main/java/com/hanghae/blog/api/like/repository/CommentLikeRepository.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/RequestCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/entity/Posting.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: feature

#92 🐛 Fix: 포스팅 생성 버그
  src/main/java/com/hanghae/blog/api/common/response/PageResponse.java
  src/main/java/com/hanghae/blog/api/posting/controller/PostingController.java
  src/main/java/com/hanghae/blog/api/posting/dto/RequestCreatePosting.java
  src/main/java/com/hanghae/blog/api/posting/dto/ResponsePagePosting.java
  src/main/java/com/hanghae/blog/api/posting/entity/Posting.java
  src/main/java/com/hanghae/blog/api/posting/mapper/PostingMapper.java
  src/main/java/com/hanghae/blog/api/posting/service/PostingService.java
Labels: bug
